/* quick styles that should eventually be used with theme provider */


const PRIMARY_LIGHT = '#8FBDD3';
const SECONDARY_LIGHT = '#E4D1B9';
const TERTIARY_LIGHT = '#A97155';
const QUATERNARY_LIGHT = '#A97155';

const PRIMARY_DARK = '#1A120B';
const SECONDARY_DARK = '#3C2A21';
const TERTIARY_DARK = '#D5CEA3';
const QUATERNARY_DARK = '#E5E5CB';

const DARK_MODE = true;

const PRIMARY_COLOR = DARK_MODE ? PRIMARY_DARK : PRIMARY_LIGHT;
const SECONDARY_COLOR = DARK_MODE ? SECONDARY_DARK : SECONDARY_LIGHT;
const TERTIARY_COLOR = DARK_MODE ? TERTIARY_DARK : TERTIARY_LIGHT;
const QUATERNARY_COLOR = DARK_MODE ? QUATERNARY_DARK : QUATERNARY_LIGHT;

export { PRIMARY_COLOR, SECONDARY_COLOR, TERTIARY_COLOR, QUATERNARY_COLOR };
